# Generated by Django 2.0.3 on 2018-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField(default=1)),
                ('platform', models.CharField(choices=[('Books', 'Books'), ('Cars', 'Cars'), ('Electronics', 'Electronics'), ('Home Appliances', 'Home Appliances'), ('Kitchen', 'Kitchen')], default='electronics', max_length=20)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('seller', models.CharField(max_length=150)),
            ],
        ),
    ]
