# Generated by Django 2.0.3 on 2018-03-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180318_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='platform',
            new_name='category',
        ),
    ]
