# Generated by Django 2.0.3 on 2018-03-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='user',
        ),
    ]
